---
title: "Flight Delays Documentation"
output: html_document
date: "2023-06-22"
---

# Context

<br>

## Business intelligence and data-driven decision making (PDA 1.1)

From this analysis, Newark Airport will be able to gain an understanding of how weather factors and other factors such as flight time and airline relate to the number of delayed flights and the length of delays at their airport. This will allow them to make better informed decisions about how to improve these numbers, as it will reveal areas that have the biggest impact that they can focus their effort on. It will also allow them to see how their performance compares to the other two airports that serve New York City. 

<br>

## Domain knowledge and the business context (PDA 1.2 & 4.7)

Newark Airport is an international airport that sits to the west of New York City, and is one of three airports that serves the city. In the year that the data was taken from, there were approximately 11600 flights that departed from Newark Airport. The airport has three runways and serves around 50 airlines. Newark has a fairly mild climate, however the airport still experiences a significant amount of flight delays. This investigation will look into any relationships between flight delays and weather, and will also delve into relationships between flight delays and other variables such as time, plane type, and airline.

<br>
<br>

# Data

<br>

## Internal and external data sources (PDA 1.4)

There were several data sources used in this investigation, both provided by the organisation (internal data), and sourced from elsewhere (external data):

- Internal Data:

  - `Flights`: This dataset held information about every flight departure from Newark, John. F Kennedy, and La Guardia airport in 2017. The data included the date of departure; the scheduled and actual departure and subsequent arrival times, and thus the calculated delay if any; the carrier (airline) for the flight; the plane tail number; the flight number; and the route information including distance and air time. (Dimensions: 303748, 19)
  
  - `Airports`: This included airport codes; airport names; geographical location of the airport including latitude, longitude, altitude; timezone information. (Dimensions: 1333, 8)
  
  - `Airlines`: Similar to `airports`, this included the airline codes and names for each carrier. (Dimensions: 12, 2)
  
  - `Planes`: This provided additional information about aircraft including their tailnumber; age; type of plane and engine; size of plane (number of engines and seats); and                    average speed. (Dimensions: 3521, 9)
  
- External Data:

  - `Weather`: This dataset was collected from three weather stations closest to each of the three airports. It included information on time and date of weather record; temperature; dewpoint; humidity; wind recordings (direction, speed, gust); precipitation amount; sea level pressure; and visibility. (Dimensions: 26201, 15)

<br>

## Types of data (PDA 2.2)
  - This investigation used a range of data types:
    - String data was used in the airline and airports data in their names and codes, as well as in the planes data from plane type, tailnumber etc, and in flights data relating to flight route
    - Date/time data was used in the departure and arrival times as well as the times of recording in `flights` and `weather`. An element of date/time data was also used in the timezone information.
    - Geospatial data was seen in the `airports` data as the latitude and longitude were used to create a map of the airports
    - Numerical data was used across the `weather` data readings and in some of the metadata from `planes` such as number of engines and seats.

<br>

## Data formats (PDA 2.3)

All data came in the format of csv files.

<br>

## 1.5 Data Quality (PDA 2.6)

The data only covered one year (2017), so it does not reflect reality well and will be biased towards the specific trends in this year that may not occur in other years. There is also a significant amount of missing data, with no obvious explanation to its absence.

<br>
<br>

# Ethics

<br>

## Ethical issues in data sourcing and extraction (PDA 2.7)

There are no ethical concerns from this data as it does not contain any sensitive information or any information regarding any specific person. 

<br>

## Ethical implications of business requirements (PDA 1.9)

The business is looking to improve its understanding of why flights are delayed and work on improving this through the factors that they can control. There is no desired outcome that would effect the wellbeing or employment of any individuals to the business, so I would say that the business requirements to not pose a threat of ethical mistreatment.

<br>
<br>

# Analysis 

<br>

## Stages in the data analysis process (PDA 1.6)

My first step in the data analysis process was to define the question I was trying to answer. I obtained the brief and worked on extracting the key issues which were:
  - What type of weather causes delays?
  - How serious are weather delays?
  - What other factors cause delays?
Once I had my key questions defined I was then able to move on to finding the data that would allow me to answer these questions.
I then collected the data that was provided, and explored each data set individually, looking at the data content and quality and gaining a sense of what components of the data sets I had would be able to answer the business questions.
Once I had decided what data was most suitable, I then began to clean the data. This involved handling empty (NA) data values, engineering new variables such as a binary delayed/not delayed column, and joining any datasets that would need to work in tandem in order to be useful, such as the `flights` details dataset and the `weather` dataset.
Once the data was cleaned and prepared for investigation, I then began looking into the data and pulling out key trends and patterns by using data visualisation techiniques. I then build three predictive models, and analysed their performance and then looked at the information they had given light to.
Once I had fully analysed the data and the predictive models, I decided on the key metrics and patterns that would best answer the questions.
I then focussed my attention on creating effective and easy to grasp visualisations and explanations of the data using my key metrics that I had selected in order to explain my findings.
I then prepared to share my results, by creating a presentation that showcased the visualisations I had created and was supported by my own explanations.

<br>

## Tools for data analysis (PDA 1.10 and 2.1)
This analysis involved the use of R and RStudio, as well as GitHub. Within R, I used various packages such as `tidyverse` and `janitor` in order to clean the data, and packages such as `ggplot` and `leaflet` to create effective plots and geographical visualisations. I also used packages such as `ranger`, `GGally`, `rpart`, `modelr` and `pROC` in order to create my predictive models.

<br>

## Descriptive, diagnostic, predictive and prescriptive analysis (PDA 1.7)

This analysis falls under several categories.
It provides descriptive analytics as it investigated flight delays from 2017, and creates an understanding based on what happened within this timeframe.
Diagnostic analytics were provided in the sense of creating an explanation into why flight delays were happening based on their relationship to weather and other factors.
The models that were built in order to predict the likelihood or length of a flight delay have provided predictive analytics as you would be able to somewhat predict the result of a flight delay based on these models. 
The analysis also provided an element of prescriptive analytics as the outcome of the predictive models exposed what factors were most correlated with a flight delay, so therefore recommends which factors and variables should be looked into and improved in order to reduce flight delay potential and length.


